### ISSUE TITLE
isFuntion returns false for async functions and generators

### ISSUE THREAD

**Issue by xcrzx** [bpmn-io/min-dash#10]
Steps to reproduce:
```js
import { isFunction } from 'min-dash';
console.log(isFunction(async function() {})) // false, should be true
console.log(isFunction(function*() {})) // false, should be true
```

**Comment by barmac** [comment]
Thank you for opening this issue.

Correct, we test only for the _ordinary_ function. We should also handle generators and async functions correctly [just like lodash does](https://github.com/lodash/lodash/blob/master/isFunction.js#L26). Feel free to create a pull request with a fix.
